version: '3.7'

networks:
  vpc:

services:
  hydra:
    image: oryd/hydra:latest-alpine
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command:
      serve all --dangerous-force-http
    environment:
      - URLS_SELF_ISSUER=http://127.0.0.1:4444
      - URLS_CONSENT=http://127.0.0.1:3000/consent
      - URLS_LOGIN=http://127.0.0.1:3000/login
      - URLS_LOGOUT=http://127.0.0.1:3000/logout
      - DSN=memory
      - SECRETS_SYSTEM=youReallyNeedToChangeThis
      - OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES=public,pairwise
      - OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT=youReallyNeedToChangeThis
    restart: unless-stopped
    networks:
      vpc:
        aliases:
          - hydra
  setup:
    image: oryd/hydra:latest-alpine
    entrypoint: /setup.sh
    depends_on:
      - hydra
    volumes:
      - ./setup.sh:/setup.sh
    networks:
      vpc:
        aliases:
          - setup
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "26500:80"
    networks:
      vpc:
        aliases:
          - proxy
  zeebe:
    image: camunda/zeebe:${ZEEBE_VERSION:-latest}
    environment:
      - ZEEBE_LOG_LEVEL=${ZEEBE_LOG_LEVEL:-debug}
      - ZEEBE_BROKER_CLUSTER_NODEID=0
    networks:
      vpc:
        aliases:
          - zeebe
