version: '3'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.13
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - discovery.type=single-node
            - cluster.name=test

    kibana:
        image: docker.elastic.co/kibana/kibana-oss:6.8.13
        ports:
            - "5601:5601"
        links:
            - elasticsearch
