version: '3.7'

networks:
  vpc:

services:
  keycloak:
    image: jboss/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/zeebe-realm.json
    restart: unless-stopped
    volumes:
      - ./zeebe-realm.json:/tmp/zeebe-realm.json
    networks:
      vpc:
        aliases:
          - keycloak
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "26500:80"
      - "4444:4444"
    networks:
      vpc:
        aliases:
          - proxy
  zeebe:
    image: camunda/zeebe:${ZEEBE_VERSION:-latest}
    environment:
      - ZEEBE_LOG_LEVEL=${ZEEBE_LOG_LEVEL:-debug}
      - ZEEBE_BROKER_CLUSTER_NODEID=0
    networks:
      vpc:
        aliases:
          - zeebe
