name: Add default labels to new issues

on:
  issues:
    types: [opened, reopened]

jobs:
  add-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Label
        uses: zeebe-io/zeebe-label-action@v1.0.1
        id: label
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels: "Status: Needs Triage"
          ignore-labeled: "^Status:.*$"
